-- =============================================================================
-- seed.sql — Logical Links CMS
--
-- ⚠️  DO NOT add auth users here.
--     Auth users must be created via the Supabase Admin API so they appear
--     in the Authentication dashboard and can sign in normally.
--
-- To seed the database run (from backend/):
--   npm run seed
--
-- That script uses supabase.auth.admin.createUser() for auth users, then
-- upserts all application data (accounts, profiles, carriers, shipments,
-- assignments) via the Supabase client.
--
-- This file is kept for reference only and is intentionally empty.
-- =============================================================================
